// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPwvL6e1zn87UlPujWH1_Hqg8GPVNSiQU',
    appId: '1:202225012572:web:81e13d479cde6761523b99',
    messagingSenderId: '202225012572',
    projectId: 'wegovroom-e77c2',
    authDomain: 'wegovroom-e77c2.firebaseapp.com',
    storageBucket: 'wegovroom-e77c2.firebasestorage.app',
    measurementId: 'G-K5WB1RZQY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDOC60h1RBALyHX1Wwl_xm_nnxTPCvpaw',
    appId: '1:202225012572:android:c32ef9602f70cb97523b99',
    messagingSenderId: '202225012572',
    projectId: 'wegovroom-e77c2',
    storageBucket: 'wegovroom-e77c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBof9umvw4x-zYrmbT5bJEy5vmPmGoi-QE',
    appId: '1:202225012572:ios:b785093ca85fed8f523b99',
    messagingSenderId: '202225012572',
    projectId: 'wegovroom-e77c2',
    storageBucket: 'wegovroom-e77c2.firebasestorage.app',
    iosBundleId: 'com.example.wegovroom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBof9umvw4x-zYrmbT5bJEy5vmPmGoi-QE',
    appId: '1:202225012572:ios:b785093ca85fed8f523b99',
    messagingSenderId: '202225012572',
    projectId: 'wegovroom-e77c2',
    storageBucket: 'wegovroom-e77c2.firebasestorage.app',
    iosBundleId: 'com.example.wegovroom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPwvL6e1zn87UlPujWH1_Hqg8GPVNSiQU',
    appId: '1:202225012572:web:b24fc746d3d41a92523b99',
    messagingSenderId: '202225012572',
    projectId: 'wegovroom-e77c2',
    authDomain: 'wegovroom-e77c2.firebaseapp.com',
    storageBucket: 'wegovroom-e77c2.firebasestorage.app',
    measurementId: 'G-S4FBYT0L98',
  );
}
